export const colors = {
  primery: "#FDFCFE",
  secondery: "#f7fafd",
  lightPink: "#f6f0fe",
  drakPink: "#c488fd",
  red: "#ff7ca5",
  lightRed: "#fff2f6",
  darkBlue: "#817bff",
  lightBlue: "#2d8cff",
  green: "#10aa7a",
  gray: "#BCC6CC",
  dashBoard: "#f9faff",
  mobileApp: "#af82ff",
  landingPage: "#ffa879",
  illustration: "#5fc690",
  designCritique: "#ff79ff",
};
